# Generated by Django 5.2.13 on 2026-04-16 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_deleted_at_doctor_is_deleted'),
        ('mappings', '0001_initial'),
        ('patients', '0002_patient_deleted_at_patient_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patientdoctormapping',
            name='unique_patient_doctor_mapping',
        ),
        migrations.AddField(
            model_name='patientdoctormapping',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdoctormapping',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='patientdoctormapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('patient', 'doctor'), name='unique_active_patient_doctor_mapping'),
        ),
    ]
